<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Recharge Platform Configuration
    |--------------------------------------------------------------------------
    */

    // Maximum automatic retry attempts per transaction
    'max_retries' => (int) env('RECHARGE_MAX_RETRIES', 3),

    // Seconds within which the same mobile+operator+type+amount is considered
    // a duplicate and rejected (prevents accidental double-charges)
    'dedup_window' => (int) env('RECHARGE_DEDUP_WINDOW', 60),

    // Queue name for recharge processing jobs
    'queue' => env('RECHARGE_QUEUE', 'recharges'),

    // Minimum recharge amount (INR)
    'min_amount' => (float) env('RECHARGE_MIN_AMOUNT', 10.00),

    // Maximum recharge amount (INR) per single transaction
    'max_amount' => (float) env('RECHARGE_MAX_AMOUNT', 10000.00),

    /*
    |--------------------------------------------------------------------------
    | Mobile Operator Prefix Detection
    | Format: 'first_4_digits' => ['operator' => 'CODE', 'circle' => 'Name']
    |--------------------------------------------------------------------------
    */
    'operator_prefixes' => [
        // ── Airtel ─────────────────────────────────────────────────────────
        '9876' => ['operator' => 'AIRTEL', 'circle' => 'Punjab'],
        '9855' => ['operator' => 'AIRTEL', 'circle' => 'Himachal Pradesh'],
        '7696' => ['operator' => 'AIRTEL', 'circle' => 'Punjab'],
        '9810' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9811' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9818' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9560' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9582' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9958' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9899' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9871' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9868' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '8010' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9903' => ['operator' => 'AIRTEL', 'circle' => 'West Bengal'],
        '9804' => ['operator' => 'AIRTEL', 'circle' => 'West Bengal'],
        '9433' => ['operator' => 'AIRTEL', 'circle' => 'West Bengal'],
        '9830' => ['operator' => 'AIRTEL', 'circle' => 'West Bengal'],
        '7439' => ['operator' => 'AIRTEL', 'circle' => 'West Bengal'],
        '9821' => ['operator' => 'AIRTEL', 'circle' => 'Mumbai'],
        '9920' => ['operator' => 'AIRTEL', 'circle' => 'Mumbai'],
        '9819' => ['operator' => 'AIRTEL', 'circle' => 'Mumbai'],
        '9867' => ['operator' => 'AIRTEL', 'circle' => 'Mumbai'],
        '9372' => ['operator' => 'AIRTEL', 'circle' => 'Maharashtra'],
        '9823' => ['operator' => 'AIRTEL', 'circle' => 'Maharashtra'],
        '9552' => ['operator' => 'AIRTEL', 'circle' => 'Maharashtra'],
        '9890' => ['operator' => 'AIRTEL', 'circle' => 'Maharashtra'],
        '9845' => ['operator' => 'AIRTEL', 'circle' => 'Karnataka'],
        '9886' => ['operator' => 'AIRTEL', 'circle' => 'Karnataka'],
        '9980' => ['operator' => 'AIRTEL', 'circle' => 'Karnataka'],
        '8050' => ['operator' => 'AIRTEL', 'circle' => 'Karnataka'],
        '9840' => ['operator' => 'AIRTEL', 'circle' => 'Tamil Nadu'],
        '9884' => ['operator' => 'AIRTEL', 'circle' => 'Tamil Nadu'],
        '9444' => ['operator' => 'AIRTEL', 'circle' => 'Tamil Nadu'],
        '8754' => ['operator' => 'AIRTEL', 'circle' => 'Tamil Nadu'],
        '9748' => ['operator' => 'AIRTEL', 'circle' => 'Kolkata'],
        '9831' => ['operator' => 'AIRTEL', 'circle' => 'Kolkata'],
        '7003' => ['operator' => 'AIRTEL', 'circle' => 'Kolkata'],
        '9573' => ['operator' => 'AIRTEL', 'circle' => 'Andhra Pradesh'],
        '9701' => ['operator' => 'AIRTEL', 'circle' => 'Andhra Pradesh'],
        '9849' => ['operator' => 'AIRTEL', 'circle' => 'Andhra Pradesh'],
        '9642' => ['operator' => 'AIRTEL', 'circle' => 'Andhra Pradesh'],
        '9999' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9997' => ['operator' => 'AIRTEL', 'circle' => 'UP West'],
        '9456' => ['operator' => 'AIRTEL', 'circle' => 'UP East'],
        '9936' => ['operator' => 'AIRTEL', 'circle' => 'UP East'],
        '7007' => ['operator' => 'AIRTEL', 'circle' => 'UP East'],
        '9760' => ['operator' => 'AIRTEL', 'circle' => 'UP West'],
        '9837' => ['operator' => 'AIRTEL', 'circle' => 'UP West'],
        '9415' => ['operator' => 'AIRTEL', 'circle' => 'UP East'],
        '9358' => ['operator' => 'AIRTEL', 'circle' => 'Rajasthan'],
        '9829' => ['operator' => 'AIRTEL', 'circle' => 'Rajasthan'],
        '9413' => ['operator' => 'AIRTEL', 'circle' => 'Rajasthan'],
        '8764' => ['operator' => 'AIRTEL', 'circle' => 'Rajasthan'],
        '9878' => ['operator' => 'AIRTEL', 'circle' => 'Punjab'],
        '9872' => ['operator' => 'AIRTEL', 'circle' => 'Punjab'],
        '9317' => ['operator' => 'AIRTEL', 'circle' => 'Punjab'],
        '9815' => ['operator' => 'AIRTEL', 'circle' => 'Punjab'],
        '9779' => ['operator' => 'AIRTEL', 'circle' => 'Haryana'],
        '9992' => ['operator' => 'AIRTEL', 'circle' => 'Haryana'],
        '9896' => ['operator' => 'AIRTEL', 'circle' => 'Haryana'],
        '8295' => ['operator' => 'AIRTEL', 'circle' => 'Haryana'],
        '9971' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9873' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '7011' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9350' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9205' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9013' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9953' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '8527' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '7042' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],
        '9654' => ['operator' => 'AIRTEL', 'circle' => 'Delhi'],

        // ── Jio ────────────────────────────────────────────────────────────
        '9090' => ['operator' => 'JIO', 'circle' => 'Maharashtra'],
        '8890' => ['operator' => 'JIO', 'circle' => 'Kerala'],
        '7000' => ['operator' => 'JIO', 'circle' => 'Madhya Pradesh'],
        '8369' => ['operator' => 'JIO', 'circle' => 'Maharashtra'],
        '9136' => ['operator' => 'JIO', 'circle' => 'Maharashtra'],
        '7008' => ['operator' => 'JIO', 'circle' => 'Odisha'],
        '7009' => ['operator' => 'JIO', 'circle' => 'Punjab'],
        '7011' => ['operator' => 'JIO', 'circle' => 'Delhi'],
        '7012' => ['operator' => 'JIO', 'circle' => 'Kerala'],
        '7013' => ['operator' => 'JIO', 'circle' => 'Andhra Pradesh'],
        '7016' => ['operator' => 'JIO', 'circle' => 'Gujarat'],
        '7018' => ['operator' => 'JIO', 'circle' => 'UP East'],
        '7019' => ['operator' => 'JIO', 'circle' => 'Karnataka'],
        '7020' => ['operator' => 'JIO', 'circle' => 'Maharashtra'],
        '7021' => ['operator' => 'JIO', 'circle' => 'Mumbai'],
        '7022' => ['operator' => 'JIO', 'circle' => 'Karnataka'],
        '7023' => ['operator' => 'JIO', 'circle' => 'Rajasthan'],
        '7025' => ['operator' => 'JIO', 'circle' => 'Kerala'],
        '7026' => ['operator' => 'JIO', 'circle' => 'Tamil Nadu'],
        '7030' => ['operator' => 'JIO', 'circle' => 'Maharashtra'],
        '7045' => ['operator' => 'JIO', 'circle' => 'Mumbai'],
        '7046' => ['operator' => 'JIO', 'circle' => 'Gujarat'],
        '7048' => ['operator' => 'JIO', 'circle' => 'Gujarat'],
        '7096' => ['operator' => 'JIO', 'circle' => 'Gujarat'],
        '7201' => ['operator' => 'JIO', 'circle' => 'Haryana'],
        '7202' => ['operator' => 'JIO', 'circle' => 'Haryana'],
        '7203' => ['operator' => 'JIO', 'circle' => 'Rajasthan'],
        '7210' => ['operator' => 'JIO', 'circle' => 'UP East'],
        '7217' => ['operator' => 'JIO', 'circle' => 'Delhi'],
        '7388' => ['operator' => 'JIO', 'circle' => 'UP East'],
        '7389' => ['operator' => 'JIO', 'circle' => 'Madhya Pradesh'],
        '7390' => ['operator' => 'JIO', 'circle' => 'West Bengal'],
        '6350' => ['operator' => 'JIO', 'circle' => 'Rajasthan'],
        '6351' => ['operator' => 'JIO', 'circle' => 'Rajasthan'],
        '6352' => ['operator' => 'JIO', 'circle' => 'Rajasthan'],
        '6353' => ['operator' => 'JIO', 'circle' => 'Rajasthan'],
        '6354' => ['operator' => 'JIO', 'circle' => 'Rajasthan'],
        '6355' => ['operator' => 'JIO', 'circle' => 'Rajasthan'],
        '8140' => ['operator' => 'JIO', 'circle' => 'Gujarat'],
        '8141' => ['operator' => 'JIO', 'circle' => 'Gujarat'],
        '8160' => ['operator' => 'JIO', 'circle' => 'Gujarat'],
        '8200' => ['operator' => 'JIO', 'circle' => 'Gujarat'],
        '9316' => ['operator' => 'JIO', 'circle' => 'Rajasthan'],
        '9773' => ['operator' => 'JIO', 'circle' => 'West Bengal'],
        '9774' => ['operator' => 'JIO', 'circle' => 'West Bengal'],

        // ── BSNL ───────────────────────────────────────────────────────────
        '9418' => ['operator' => 'BSNL', 'circle' => 'Himachal Pradesh'],
        '9459' => ['operator' => 'BSNL', 'circle' => 'Himachal Pradesh'],
        '9419' => ['operator' => 'BSNL', 'circle' => 'Jammu & Kashmir'],
        '9469' => ['operator' => 'BSNL', 'circle' => 'Jammu & Kashmir'],
        '9103' => ['operator' => 'BSNL', 'circle' => 'Jammu & Kashmir'],
        '9622' => ['operator' => 'BSNL', 'circle' => 'Jammu & Kashmir'],
        '9419' => ['operator' => 'BSNL', 'circle' => 'Jammu & Kashmir'],
        '9436' => ['operator' => 'BSNL', 'circle' => 'Northeast'],
        '9862' => ['operator' => 'BSNL', 'circle' => 'Northeast'],
        '9435' => ['operator' => 'BSNL', 'circle' => 'Assam'],
        '9435' => ['operator' => 'BSNL', 'circle' => 'Assam'],
        '9401' => ['operator' => 'BSNL', 'circle' => 'Assam'],
        '9476' => ['operator' => 'BSNL', 'circle' => 'Assam'],
        '9472' => ['operator' => 'BSNL', 'circle' => 'Bihar'],
        '9934' => ['operator' => 'BSNL', 'circle' => 'Bihar'],
        '9430' => ['operator' => 'BSNL', 'circle' => 'Bihar'],
        '9431' => ['operator' => 'BSNL', 'circle' => 'Bihar'],
        '9933' => ['operator' => 'BSNL', 'circle' => 'Sikkim'],
        '7085' => ['operator' => 'BSNL', 'circle' => 'UP East'],
        '9415' => ['operator' => 'BSNL', 'circle' => 'UP East'],
        '7081' => ['operator' => 'BSNL', 'circle' => 'UP East'],
        '9450' => ['operator' => 'BSNL', 'circle' => 'UP East'],
        '9451' => ['operator' => 'BSNL', 'circle' => 'UP East'],
        '8004' => ['operator' => 'BSNL', 'circle' => 'UP East'],
        '9936' => ['operator' => 'BSNL', 'circle' => 'UP East'],
        '9453' => ['operator' => 'BSNL', 'circle' => 'UP West'],
        '9760' => ['operator' => 'BSNL', 'circle' => 'UP West'],
        '9412' => ['operator' => 'BSNL', 'circle' => 'UP West'],
        '9927' => ['operator' => 'BSNL', 'circle' => 'UP West'],
        '9838' => ['operator' => 'BSNL', 'circle' => 'UP West'],
        '9407' => ['operator' => 'BSNL', 'circle' => 'Madhya Pradesh'],
        '9425' => ['operator' => 'BSNL', 'circle' => 'Madhya Pradesh'],
        '9111' => ['operator' => 'BSNL', 'circle' => 'Madhya Pradesh'],
        '8109' => ['operator' => 'BSNL', 'circle' => 'Madhya Pradesh'],
        '9414' => ['operator' => 'BSNL', 'circle' => 'Rajasthan'],
        '9413' => ['operator' => 'BSNL', 'circle' => 'Rajasthan'],
        '8104' => ['operator' => 'BSNL', 'circle' => 'Rajasthan'],
        '9461' => ['operator' => 'BSNL', 'circle' => 'Rajasthan'],
        '9462' => ['operator' => 'BSNL', 'circle' => 'Rajasthan'],
        '9416' => ['operator' => 'BSNL', 'circle' => 'Haryana'],
        '9466' => ['operator' => 'BSNL', 'circle' => 'Haryana'],
        '8816' => ['operator' => 'BSNL', 'circle' => 'Haryana'],
        '9417' => ['operator' => 'BSNL', 'circle' => 'Punjab'],
        '9464' => ['operator' => 'BSNL', 'circle' => 'Punjab'],
        '8427' => ['operator' => 'BSNL', 'circle' => 'Punjab'],
        '8872' => ['operator' => 'BSNL', 'circle' => 'Punjab'],
        '9434' => ['operator' => 'BSNL', 'circle' => 'West Bengal'],
        '9432' => ['operator' => 'BSNL', 'circle' => 'West Bengal'],
        '8334' => ['operator' => 'BSNL', 'circle' => 'West Bengal'],
        '9474' => ['operator' => 'BSNL', 'circle' => 'Odisha'],
        '9437' => ['operator' => 'BSNL', 'circle' => 'Odisha'],
        '9040' => ['operator' => 'BSNL', 'circle' => 'Odisha'],
        '9438' => ['operator' => 'BSNL', 'circle' => 'Odisha'],
        '9447' => ['operator' => 'BSNL', 'circle' => 'Kerala'],
        '9446' => ['operator' => 'BSNL', 'circle' => 'Kerala'],
        '9496' => ['operator' => 'BSNL', 'circle' => 'Kerala'],
        '9744' => ['operator' => 'BSNL', 'circle' => 'Kerala'],
        '9423' => ['operator' => 'BSNL', 'circle' => 'Maharashtra'],
        '9422' => ['operator' => 'BSNL', 'circle' => 'Maharashtra'],
        '8600' => ['operator' => 'BSNL', 'circle' => 'Maharashtra'],
        '9442' => ['operator' => 'BSNL', 'circle' => 'Tamil Nadu'],
        '9443' => ['operator' => 'BSNL', 'circle' => 'Tamil Nadu'],
        '9445' => ['operator' => 'BSNL', 'circle' => 'Tamil Nadu'],
        '8056' => ['operator' => 'BSNL', 'circle' => 'Tamil Nadu'],
        '9448' => ['operator' => 'BSNL', 'circle' => 'Karnataka'],
        '9449' => ['operator' => 'BSNL', 'circle' => 'Karnataka'],
        '8971' => ['operator' => 'BSNL', 'circle' => 'Karnataka'],
        '9440' => ['operator' => 'BSNL', 'circle' => 'Andhra Pradesh'],
        '9441' => ['operator' => 'BSNL', 'circle' => 'Andhra Pradesh'],
        '9491' => ['operator' => 'BSNL', 'circle' => 'Andhra Pradesh'],
        '8019' => ['operator' => 'BSNL', 'circle' => 'Andhra Pradesh'],
        '9426' => ['operator' => 'BSNL', 'circle' => 'Gujarat'],
        '9427' => ['operator' => 'BSNL', 'circle' => 'Gujarat'],
        '8000' => ['operator' => 'BSNL', 'circle' => 'Gujarat'],
        '8128' => ['operator' => 'BSNL', 'circle' => 'Gujarat'],

        // ── Vi (Vodafone-Idea) ──────────────────────────────────────────────
        '9888' => ['operator' => 'VI', 'circle' => 'Punjab'],
        '9814' => ['operator' => 'VI', 'circle' => 'Punjab'],
        '9815' => ['operator' => 'VI', 'circle' => 'Punjab'],
        '7087' => ['operator' => 'VI', 'circle' => 'Punjab'],
        '9855' => ['operator' => 'VI', 'circle' => 'Punjab'],
        '9216' => ['operator' => 'VI', 'circle' => 'Punjab'],
        '7027' => ['operator' => 'VI', 'circle' => 'Punjab'],
        '9212' => ['operator' => 'VI', 'circle' => 'Delhi'],
        '9213' => ['operator' => 'VI', 'circle' => 'Delhi'],
        '9311' => ['operator' => 'VI', 'circle' => 'Delhi'],
        '9810' => ['operator' => 'VI', 'circle' => 'Delhi'],
        '9717' => ['operator' => 'VI', 'circle' => 'Delhi'],
        '9811' => ['operator' => 'VI', 'circle' => 'Delhi'],
        '7838' => ['operator' => 'VI', 'circle' => 'Delhi'],
        '9820' => ['operator' => 'VI', 'circle' => 'Mumbai'],
        '9821' => ['operator' => 'VI', 'circle' => 'Mumbai'],
        '9833' => ['operator' => 'VI', 'circle' => 'Mumbai'],
        '9930' => ['operator' => 'VI', 'circle' => 'Mumbai'],
        '9324' => ['operator' => 'VI', 'circle' => 'Mumbai'],
        '8080' => ['operator' => 'VI', 'circle' => 'Mumbai'],
        '9850' => ['operator' => 'VI', 'circle' => 'Maharashtra'],
        '9921' => ['operator' => 'VI', 'circle' => 'Maharashtra'],
        '9890' => ['operator' => 'VI', 'circle' => 'Maharashtra'],
        '8308' => ['operator' => 'VI', 'circle' => 'Maharashtra'],
        '9844' => ['operator' => 'VI', 'circle' => 'Karnataka'],
        '9900' => ['operator' => 'VI', 'circle' => 'Karnataka'],
        '9620' => ['operator' => 'VI', 'circle' => 'Karnataka'],
        '8867' => ['operator' => 'VI', 'circle' => 'Karnataka'],
        '9843' => ['operator' => 'VI', 'circle' => 'Tamil Nadu'],
        '9842' => ['operator' => 'VI', 'circle' => 'Tamil Nadu'],
        '9894' => ['operator' => 'VI', 'circle' => 'Tamil Nadu'],
        '8122' => ['operator' => 'VI', 'circle' => 'Tamil Nadu'],
        '9847' => ['operator' => 'VI', 'circle' => 'Kerala'],
        '9846' => ['operator' => 'VI', 'circle' => 'Kerala'],
        '9995' => ['operator' => 'VI', 'circle' => 'Kerala'],
        '7025' => ['operator' => 'VI', 'circle' => 'Kerala'],
        '9726' => ['operator' => 'VI', 'circle' => 'Gujarat'],
        '9824' => ['operator' => 'VI', 'circle' => 'Gujarat'],
        '8141' => ['operator' => 'VI', 'circle' => 'Gujarat'],
        '9904' => ['operator' => 'VI', 'circle' => 'Gujarat'],
        '9799' => ['operator' => 'VI', 'circle' => 'Rajasthan'],
        '9950' => ['operator' => 'VI', 'circle' => 'Rajasthan'],
        '8890' => ['operator' => 'VI', 'circle' => 'Rajasthan'],
        '9828' => ['operator' => 'VI', 'circle' => 'Rajasthan'],
        '9412' => ['operator' => 'VI', 'circle' => 'UP West'],
        '9897' => ['operator' => 'VI', 'circle' => 'UP West'],
        '9457' => ['operator' => 'VI', 'circle' => 'UP West'],
        '8006' => ['operator' => 'VI', 'circle' => 'UP West'],
        '9935' => ['operator' => 'VI', 'circle' => 'UP East'],
        '9452' => ['operator' => 'VI', 'circle' => 'UP East'],
        '9455' => ['operator' => 'VI', 'circle' => 'UP East'],
        '9918' => ['operator' => 'VI', 'circle' => 'UP East'],
        '9934' => ['operator' => 'VI', 'circle' => 'Bihar'],
        '9006' => ['operator' => 'VI', 'circle' => 'Bihar'],
        '7463' => ['operator' => 'VI', 'circle' => 'Bihar'],
        '9932' => ['operator' => 'VI', 'circle' => 'West Bengal'],
        '9883' => ['operator' => 'VI', 'circle' => 'West Bengal'],
        '9831' => ['operator' => 'VI', 'circle' => 'West Bengal'],
        '7980' => ['operator' => 'VI', 'circle' => 'West Bengal'],
        '9853' => ['operator' => 'VI', 'circle' => 'Odisha'],
        '8280' => ['operator' => 'VI', 'circle' => 'Odisha'],
        '9937' => ['operator' => 'VI', 'circle' => 'Odisha'],
        '7681' => ['operator' => 'VI', 'circle' => 'Odisha'],
        '9438' => ['operator' => 'VI', 'circle' => 'Odisha'],
        '9860' => ['operator' => 'VI', 'circle' => 'Andhra Pradesh'],
        '9703' => ['operator' => 'VI', 'circle' => 'Andhra Pradesh'],
        '9885' => ['operator' => 'VI', 'circle' => 'Andhra Pradesh'],
        '8520' => ['operator' => 'VI', 'circle' => 'Andhra Pradesh'],
        '9575' => ['operator' => 'VI', 'circle' => 'Madhya Pradesh'],
        '9406' => ['operator' => 'VI', 'circle' => 'Madhya Pradesh'],
        '9926' => ['operator' => 'VI', 'circle' => 'Madhya Pradesh'],
        '6260' => ['operator' => 'VI', 'circle' => 'Madhya Pradesh'],
        '9872' => ['operator' => 'VI', 'circle' => 'Punjab'],
        '9878' => ['operator' => 'VI', 'circle' => 'Punjab'],
        '8837' => ['operator' => 'VI', 'circle' => 'Punjab'],
        '9779' => ['operator' => 'VI', 'circle' => 'Haryana'],
        '9996' => ['operator' => 'VI', 'circle' => 'Haryana'],
        '9991' => ['operator' => 'VI', 'circle' => 'Haryana'],
        '8816' => ['operator' => 'VI', 'circle' => 'Haryana'],
        '9748' => ['operator' => 'VI', 'circle' => 'Kolkata'],
        '9674' => ['operator' => 'VI', 'circle' => 'Kolkata'],
        '7044' => ['operator' => 'VI', 'circle' => 'Kolkata'],
        '9163' => ['operator' => 'VI', 'circle' => 'Kolkata'],
    ],

    /*
    |--------------------------------------------------------------------------
    | API Callback Security
    |--------------------------------------------------------------------------
    */
    'callback_secret' => env('RECHARGE_CALLBACK_SECRET', ''),

    /*
    |--------------------------------------------------------------------------
    | Commission Calculation Mode
    | Options: 'percentage' | 'flat'
    |--------------------------------------------------------------------------
    */
    'commission_mode' => env('RECHARGE_COMMISSION_MODE', 'percentage'),

];
